spring.application.name=ms-campuslab-report

server.port=${SERVER_PORT:8084}

services.bookings.url=${BOOKINGS_SERVICE_URL:http://localhost:8081}
services.catalog.url=${CATALOG_SERVICE_URL:http://localhost:8082}

management.endpoints.web.exposure.include=health